name: Lib Publish

on:
  push:
    branches:
      - main
    paths:
      - package.json

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: "yarn"

      - name: Install
        run: yarn install --immutable

      - name: Check
        run: yarn exec vp check

      - name: Build
        run: yarn exec vp pack

      - name: Test
        run: yarn exec vp test run

      - name: Publish "tiwi"
        uses: JS-DevTools/npm-publish@v4
        with:
          access: public
