name: Lib Publish

on:
  push:
    branches:
      - main
    paths:
      - package.json

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: Build
        run: |
          yarn install --immutable
          yarn build

      - name: Test
        run: |
          yarn test

      - name: Publish "tiwi"
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
